macos_min_version:
  - 10.15  # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.15  # [osx and x86_64]
MACOSX_SDK_VERSION:
  - "10.15"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk        # [osx and x86_64]
cxx_compiler:  # [win]
  - vs2019     # [win]