
# https://github.com/rdkit/rdkit/blob/0ece02e9254ef2d5eeade2bd40eb13546522dbd3/External/Eigen/CMakeLists.txt#L2
eigen:
  - 3.4.0
# https://github.com/rdkit/rdkit/blob/0ece02e9254ef2d5eeade2bd40eb13546522dbd3/Code/MinimalLib/docker/Dockerfile_1_deps#L22
freetype:
  - 2.13.3
