{% set name = "rdkit" %}
{% set version = "2025.03.5" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ filename }}
  sha256: 8bdb3c774ed4ae9e2727b6ce005004191447d630d8e857d36839cd8f1bca55b5
  patches:
    - 0001_fix_source.patch

build:
  number: 0
  # We skip s390x because it's not supported.
  skip: True # [py<37 or s390x]
  run_exports:
    - {{ pin_subpackage('rdkit', max_pin='x.x.x') }}
  ignore_run_exports:
    - numpy
    - libcxx            # [unix]
    - ucrt              # [win]
    - vc14_runtime      # [win]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python
    - numpy
    - cmake >=3.16
    # Tests are using catch2 which is unavailable on the main channel,
    # using vendored one instead
    - git                                    # [linux]
    - jom                                    # [win]
    - make                                   # [unix]
    - pkg-config
  host:
    - libboost-devel {{ boost }}
    - libboost-python-devel {{ boost }}
    - eigen {{ eigen }}
    - freetype {{ freetype }}
    - python
    # Required for tests
    - pytest
    - numpy {{ numpy }}
    - pillow >=10.4.0
    - pandas >=2.2.3
    - setuptools >=58.0.4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.Chem.Draw
    - rdkit.Chem.Draw.rdMolDraw2D
    - rdkit.Chem.rdFreeSASA
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib
  requires:
    - pip
  commands:
    - pip check
    - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
    - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1   # [win]

about:
  home: https://rdkit.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  description: |
      RDKit is open-source cheminformatics software comprised of core modules written in C++, and optional
      wrappers for Python, Java, and C#. It supports 2D and 3D molecular operations, descriptor generation
      for machine learning, and cheminformatics nodes for KNIME, among other features.
  doc_url: https://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
    - jaimergp
    - sumit0190
