{% set name = "rdkit" %}
{% set version = "2023.03.3" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ filename }}
  sha256: bdbf9a2e6988526bfeb8c56ce3cdfe2998d60ac289078e2215374288185e8c8d

build:
  number: 0
  # We skip s390x because it's not supported.
  skip: True # [py<37 or s390x]
  missing_dso_whitelist:
    - '*/RDKit*dll'  # [win]
  run_exports:
    - {{ pin_subpackage('rdkit', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - numpy
    - cmake
    - jom                                    # [win]
    - make                                   # [unix]
    - pkg-config
  host:
    - boost-cpp 1.73                         # [win]
    - libboost 1.73                          # [win]
    - py-boost 1.73                          # [win]
    - libboost 1.82                          # [not win]
    - py-boost 1.82                          # [not win]
    - eigen
    - freetype
    - python
    - numpy {{ numpy }}
    - pillow
    - pandas
    - setuptools
    - wheel
  run:
    - libboost >=1.73.0,<1.73.1.0a0 # [win]
    - libboost >=1.82.0,<1.82.1.0a0 # [not win]
    - py-boost
    - python
    - pillow
    - pandas
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - sqlalchemy
    - reportlab

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.Chem.Draw
    - rdkit.Chem.rdFreeSASA
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib
  requires:
    - pip
  commands:
    - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
    - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1   # [win]

about:
  home: https://rdkit.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  description: |
      RDKit is open-source cheminformatics software comprised of core modules written in C++, and optional
      wrappers for Python, Java, and C#. It supports 2D and 3D molecular operations, descriptor generation
      for machine learning, and cheminformatics nodes for KNIME, among other features.
  doc_url: https://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
    - jaimergp
    - sumit0190
