{% set name = "rdkit" %}
{% set version = "2023.03.2" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: bb43216b075b93b767e6cbaecd5e95d087da887bcdc51afd36d940d8bd9f9819

build:
  number: 0
  # We skip s390x because it's not supported.
  skip: True # [s390x]
  skip: True # [py<37]
  missing_dso_whitelist:
    - '*/RDKit*dll'  # [win]
  run_exports:
    - {{ pin_subpackage('rdkit', max_pin='x.x.x') }}
  ignore_run_exports:
    # This is not required by any library, it's just exported by cairo.
    - pixman

requirements:
  build:
    - {{ compiler('cxx') }}
    - numpy
    - cmake
    - ninja
    - pkg-config
  host:
    - boost-cpp 1.73.0                             # [win]
    - cairo
    - eigen 3.3.7
    - freetype
    - libboost 1.73.0
    - numpy
    - pandas
    - pillow
    - py-boost 1.73.0
    - python
    - setuptools
    - wheel
  run:
    - {{ pin_compatible('numpy') }}
    - cairo >=1.16.0,<2.0a0
    - libboost >=1.73.0,<1.73.1.0a0
    - matplotlib-base
    - pandas
    - pillow
    - py-boost
    - pycairo
    - python
    - reportlab
    - sqlalchemy

test:
  commands:
    - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
    - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1   # [win]
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.Chem.rdFreeSASA
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib

about:
  home: https://rdkit.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  description: |
      RDKit is open-source cheminformatics software comprised of core modules written in C++, and optional
      wrappers for Python, Java, and C#. It supports 2D and 3D molecular operations, descriptor generation
      for machine learning, and cheminformatics nodes for KNIME, among other features.
  doc_url: https://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
    - jaimergp
    - sumit0190
