{% set name = "rdkit" %}
{% set version = "2025.09.6" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ filename }}
  sha256: 57b92e8f47d9dbd559bd808d5cf6c48a628bc36118bc35b832a35e2ca8a0c7a1

build:
  number: 0
  # TODO: remove skip py314 once libboost-python-devel for py314 available
  skip: True # [py<37 or py>=314]
  run_exports:
    - {{ pin_subpackage('rdkit', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python
    - numpy
    - cmake >=3.16
    # Tests are using catch2 which is unavailable on the main channel,
    # using vendored one instead
    - git
    - jom                                    # [win]
    - make                                   # [unix]
    - pkg-config                             # [unix]
  host:
    - libboost-devel {{ libboost }}
    - libboost-python-devel {{ libboost }}
    - eigen {{ eigen }}
    - freetype {{ freetype }}
    - python
    # Required for build layer tests
    - pytest
    - numpy {{ numpy }}
    - pillow
    - pandas >=2.2.3
    - setuptools >=58.0.4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib-base
    - reportlab
    - sqlalchemy
    - pillow

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.Chem.Draw
    - rdkit.Chem.Draw.rdMolDraw2D
    - rdkit.Chem.rdFreeSASA
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib
  requires:
    - pip
  commands:
    - pip check
    - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"

    # Unix: headers
    - test -f "${PREFIX}/include/rdkit/Catalogs/Catalog.h"                                     # [unix]
    - test -f "${PREFIX}/include/rdkit/GraphMol/ROMol.h"                                       # [unix]
    - test -f "${PREFIX}/include/rdkit/GraphMol/Descriptors/MolDescriptors.h"                  # [unix]

    # Unix: core shared libs
    - test -f "${PREFIX}/lib/libRDKitGraphMol${SHLIB_EXT}"                                     # [unix]
    - test -f "${PREFIX}/lib/libRDKitSmilesParse${SHLIB_EXT}"                                  # [unix]
    - test -f "${PREFIX}/lib/libRDKitMolDraw2D${SHLIB_EXT}"                                    # [unix]
    - test -f "${PREFIX}/lib/libRDKitChemReactions${SHLIB_EXT}"                                # [unix]

    # Unix: python package files
    - test -f "${SP_DIR}/rdkit/__init__.py"                                                    # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/__init__.py"                                               # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/AllChem.py"                                                # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/Draw/FreeSans.ttf"                                         # [unix]

    # Unix: compiled python extensions
    - test -f "${SP_DIR}/rdkit/Chem/rdchem.so"                                                 # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/rdMolDescriptors.so"                                       # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/rdMolAlign.so"                                             # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/rdinchi.so"                                                # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/rdFreeSASA.so"                                             # [unix]
    - test -f "${SP_DIR}/rdkit/Chem/MolStandardize/rdMolStandardize.so"                        # [unix]
    - test -f "${SP_DIR}/rdkit/Avalon/pyAvalonTools.so"                                        # [unix]

    # Windows: headers
    - if not exist %LIBRARY_INC%\rdkit\Catalogs\Catalog.h exit 1                               # [win]
    - if not exist %LIBRARY_INC%\rdkit\GraphMol\ROMol.h exit 1                                 # [win]
    - if not exist %LIBRARY_INC%\rdkit\GraphMol\Descriptors\MolDescriptors.h exit 1            # [win]

    # Windows: core import libs / dlls
    - if not exist %LIBRARY_LIB%\RDKitGraphMol.lib exit 1                                      # [win]
    - if not exist %LIBRARY_LIB%\RDKitSmilesParse.lib exit 1                                   # [win]
    - if not exist %LIBRARY_LIB%\RDKitMolDraw2D.lib exit 1                                     # [win]
    - if not exist %LIBRARY_LIB%\RDKitChemReactions.lib exit 1                                 # [win]

    # Windows: python package files
    - if not exist %SP_DIR%\rdkit\__init__.py exit 1                                           # [win]
    - if not exist %SP_DIR%\rdkit\Chem\__init__.py exit 1                                      # [win]
    - if not exist %SP_DIR%\rdkit\Chem\AllChem.py exit 1                                       # [win]
    - if not exist %SP_DIR%\rdkit\Chem\Draw\FreeSans.ttf exit 1                                # [win]

    # Windows: compiled python extensions
    - if not exist %SP_DIR%\rdkit\Chem\rdchem.pyd exit 1                                       # [win]
    - if not exist %SP_DIR%\rdkit\Chem\rdMolDescriptors.pyd exit 1                             # [win]
    - if not exist %SP_DIR%\rdkit\Chem\rdMolAlign.pyd exit 1                                   # [win]
    - if not exist %SP_DIR%\rdkit\Chem\rdinchi.pyd exit 1                                      # [win]
    - if not exist %SP_DIR%\rdkit\Chem\rdFreeSASA.pyd exit 1                                   # [win]
    - if not exist %SP_DIR%\rdkit\Chem\MolStandardize\rdMolStandardize.pyd exit 1              # [win]
    - if not exist %SP_DIR%\rdkit\Avalon\pyAvalonTools.pyd exit 1

about:
  home: https://rdkit.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  description: |
      RDKit is open-source cheminformatics software comprised of core modules written in C++, and optional
      wrappers for Python, Java, and C#. It supports 2D and 3D molecular operations, descriptor generation
      for machine learning, and cheminformatics nodes for KNIME, among other features.
  doc_url: https://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
    - jaimergp
    - sumit0190
