appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: w4J2CWBqvL5DtUD/C2ol2Sz2z8LLGTp/oDmhCnQq4DRRiHFkoc+y8yOQr7yqcZT7kCT0uljg6TjdzbDtu1icI309wvskGodVvc23wu3xHIC8kz7syBmNnt2P2jgb98z8ex7LEncPxiuBttuFsz1Zp3Xv4ZtHXQlMO4EOqFndAk8EBXnSFOEb8Pu5AK9evc0tCrCXsaq4r4cZiv+7zmWIVAOOF4VHv7OF1PEikZ3vmSEzvK/iNt2ESLoTBJSzz/t0V3Ui1Rec7nKt171Euk/CFL2ls/LCB6saDYjyQZW9gpm31ppFVFOO+55Fk9i+aGBDlbbYQ6D45o01uvUUY9F0iKf12CEZRDtUriF6ZJSPipB+SNWRe6K1FQAGIHxZi0RMdQ/R0SRbQvy7ElxLyzttnDKIbNNllqUrP/vN3cnup8gdFVf+dWieTk4tUX0aJNxITsJAT7loGSnYQsJWf01A+11t6IQWBL3iZWufTTbNT7K3IR1kpFICCUoix27/wctvoG64eDSq+lBXFA3fhogSqtmi7YRu3yieMYs+Kv7Ns645ZycyrQAs9N/e0evqRXLFs9BoGpj70ucGdk/q5IGsB6lHP0tO0cSitZSf3tFVgg4nX1IQ6hvWJ3SMwtys2pN63q6qONq8dv6k7QNku1OhjBmhZSot/GgOpKPsFtKJ7xY=}
provider:
  win: azure
conda_forge_output_validation: true
